### PR TITLE
Fix `.gitignore` during app initialization

### LINKED ISSUE #42: `.gitignore` is not created
Hey hey 👋 

I was trying to create a `basic-ts` robawt just now and when I was gonna make the inital git commit it included the `node_modules/` folder. It seems like the `.gitignore` file is not created when using `create-probot-app`. Not sure about other templates then `basic-ts` though.

Here's the output with the `npm install` output omitted:

```sh
☁  koddsson  npx create-probot-app temp

Let's create a Probot app!
Hit enter to accept the suggestion.

? App name: temp
? Description of app: A Probot app
? Author's full name: Kristján Oddsson
? Author's email address: koddsson@gmail.com
? Homepage:
? GitHub user or org name: koddsson
? Repository name: temp
? Which template would you like to use? basic-ts
created file: /Users/kristjanoddsson/koddsson/temp/.env.example
created file: /Users/kristjanoddsson/koddsson/temp/.travis.yml
created file: /Users/kristjanoddsson/koddsson/temp/CODE_OF_CONDUCT.md
created file: /Users/kristjanoddsson/koddsson/temp/CONTRIBUTING.md
created file: /Users/kristjanoddsson/koddsson/temp/LICENSE
created file: /Users/kristjanoddsson/koddsson/temp/README.md
created file: /Users/kristjanoddsson/koddsson/temp/app.yml
created file: /Users/kristjanoddsson/koddsson/temp/jest.config.js
created file: /Users/kristjanoddsson/koddsson/temp/package.json
created file: /Users/kristjanoddsson/koddsson/temp/tsconfig.json
created file: /Users/kristjanoddsson/koddsson/temp/src/index.ts
created file: /Users/kristjanoddsson/koddsson/temp/test/index.test.ts
created file: /Users/kristjanoddsson/koddsson/temp/test/fixtures/issues.opened.json
Finished scaffolding files!

Installing Node dependencies!

npm notice created a lockfile as package-lock.json. You should commit this file.
added 1049 packages from 610 contributors and audited 20747 packages in 19.721s
found 0 vulnerabilities


Done! Enjoy building your Probot app!
☁  koddsson  cat temp/.gitignore
cat: temp/.gitignore: No such file or directory
☁  koddsson
```

### LINKED ISSUE #69: Missing .gitignore file
Hello Probot team;
I've noticed that when generating a bot from a template, the `.gitignore` file is never copied.
Which means that it always has to be added manually after 

This is also related to https://github.com/probot/create-probot-app/issues/42

### PR DESCRIPTION
**Pull request by MaximDevoir**
This PR properly handles `.gitignore` during app creation

## Issues

This PR fixes #42, and fixes #69.

### CODE REVIEW

**Comment by MaximDevoir** [comment]
Edge case: Because create-probot-app is idempotent, if a file is named `gitignore` in the directory of the initializing Probot app, no `.gitignore` file will be created.

File: bin/create-probot-app.js [hunk 1]
```diff
@@ -145,14 +146,34 @@ inquirer.prompt(prompts)
   })
   .then(results => {
     results.forEach(fileinfo => {
+      if (fileinfo.skipped === false &&
+        path.basename(fileinfo.path) === 'gitignore'
```
Comment (MaximDevoir) [inline bin/create-probot-app.js]: Edge case: Because create-probot-app is idempotent, if a file is named gitignore in the directory of the initializing Probot app, no .gitignore file will be created.
